syslinux: Fix no buildable providers on AArch64
syslinux/syslinux-native recipes required only on x86/x86_64
architecture. This patch avoids the following error message
while doing luvOS build natively on ARM64 architecture.
...
[build]$ bitbake luv-live-image
Parsing recipes: 100% || Time: 00:01:25
Parsing of 908 .bb files complete (0 cached, 908 parsed). 1308 targets, 81 skipp
ed, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'syslinux-native'
ERROR: syslinux-native was skipped: incompatible with host aarch64-linux (not in
COMPATIBLE_HOST)
ERROR: Required build target 'luv-live-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['luv-live-image', 'syslinux-native
']
As suggested by Matt Fleming,  I have used a single variable name for both
syslinux/syslinux-native and split those using backslash.

Signed-off-by: Naresh Bhat <naresh.bhat@linaro.org>
Suggested-by: Matt Fleming <matt.fleming@intel.com>