luv-netboot-image: set EFI_USEXORRISO variable
Even though we don't build any ISO images for netboot, image-live.bbclass has
been made to depend on syslinux. This is because, by default, this class
uses uses mkisofs to build ISO images. We can instruct such class to use
xorriso instead. This is done by setting the variable EFI_USEXORRISO. Using
this variable causes the dependency on syslinux to be eliminated.

Again, this does not have anything to do with building ISO images but with
meeting the dependency chains in bitbake.

By not setting EFI_USEXORRISO, we run into the following error:

ERROR: Nothing PROVIDES 'syslinux'
ERROR: syslinux was skipped: incompatible with host aarch64-oe-linux (not in
       COMPATIBLE_HOST)
ERROR: Required build target 'luv-netboot-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['luv-netboot-image', 'syslinux']

Reported-by: Naresh Bhat <naresh.bhat@linaro.org>
Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>